// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO9IyEqmBVv12P3DNgX_j0X1kiWExSGK4',
    appId: '1:530694555942:web:f971d0e638aa3ef1bed9e7',
    messagingSenderId: '530694555942',
    projectId: 'health-verse-a89f6',
    authDomain: 'health-verse-a89f6.firebaseapp.com',
    storageBucket: 'health-verse-a89f6.appspot.com',
    measurementId: 'G-B856Z16B61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhCB8gT5UrSyOUkPcdi-03OLNdrhdQNlE',
    appId: '1:530694555942:android:90627089104d8167bed9e7',
    messagingSenderId: '530694555942',
    projectId: 'health-verse-a89f6',
    storageBucket: 'health-verse-a89f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfvFaUMQYi1ovbTFKAI_lmY9EOgFnosYM',
    appId: '1:530694555942:ios:36559acd45cd9832bed9e7',
    messagingSenderId: '530694555942',
    projectId: 'health-verse-a89f6',
    storageBucket: 'health-verse-a89f6.appspot.com',
    iosClientId: '530694555942-k8dev59n0g020g7aats1f7gmrcod0hvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfvFaUMQYi1ovbTFKAI_lmY9EOgFnosYM',
    appId: '1:530694555942:ios:36559acd45cd9832bed9e7',
    messagingSenderId: '530694555942',
    projectId: 'health-verse-a89f6',
    storageBucket: 'health-verse-a89f6.appspot.com',
    iosClientId: '530694555942-k8dev59n0g020g7aats1f7gmrcod0hvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthverse',
  );
}
